CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE users(
	ID_PESSOA INT PRIMARY KEY NOT NULL auto_increment,
    NOME VARCHAR(45),
    TELEFONE VARCHAR(45),
    EMAIL VARCHAR(45),
    SENHA VARCHAR (45)
    );
    
    INSERT INTO users ( NOME, TELEFONE, EMAIL,SENHA) VALUES ('MURILLO','986076606','MURILLO10@GMAIL.COM','M123');
    
    SELECT * FROM users;
  
    


	
